name: Taxi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["310", "311", "312", "313"]

    steps:
      - uses: actions/checkout@v3

      - name: "Cache Nix store"
        uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: ${{ runner.os }}-nix-store-${{ matrix.python-version }}-${{ hashFiles('flake.lock') }}

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: "Import Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: "nix-store --import < /tmp/nixcache"

      - name: Run taxi tests
        run: nix build -L .#checks.x86_64-linux.taxi-python${{ matrix.python-version }}

      - name: Build taxi with all plugins
        run: nix build -L .#taxi-with-all-plugins

      - name: "Export Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
